#Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-transaction
  namespace: exam2
  labels:
    app: app-transaction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-transaction
  template:
    metadata:
      labels:
        app: app-transaction
    spec:
      containers:
      - name: app-transaction
        image: sleeptight/app-transaction:0.1.0
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8082
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
# Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: app-transaction
  labels:
    app: app-transaction
  namespace: exam2
spec:
  selector:
    app: app-transaction
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
  