apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pay-bd-replicaset
  namespace: exam2
  labels:
    app: pay-bd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pay-bd
  template:
    metadata:
      labels:
        app: pay-bd
    spec:
      containers:
      - name: pay-bd
        image: sleeptight/app-pay-sql:0.1.0
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bd-pay
  namespace: exam2
spec:
  selector:
    app: pay-bd
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306